### PR TITLE
Add technical id to shoot metrics

### PR DESCRIPTION
**Pull request by robinschneider**
**What this PR does / why we need it**:
This PR adds the technical id to all shoot related metrics.
This allows to compare metrics to create inhibit rules in Alertmanager.

**Which issue(s) this PR fixes**:
Fixes n.a.

**Special notes for your reviewer**:

**Release note**:

```improvement operator
Add `technical_id` to `garden_shoot_.+` metrics
```

### CODE REVIEW

**Comment by gardener-robot-ci-3** [comment]
Thank you @robinschneider for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Review by vicwicker — APPROVED** [review]
Thanks @robinschneider for your contribution.

**Pull request merged**
